# -*- coding: utf-8 -*-
"""fake coins

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sAvBrkzJ8EtKVYqKSr9bwJwtv1IrrpEc
"""

def find_fake_coin():
    coins = list(map(int,input().split()))
    cek_koin = {}
    n = len(coins)
    for i in range(1, n):
        if coins[i] not in cek_koin:
            cek_koin[coins[i]] = 1
        else:
            cek_koin[coins[i]] += 1
    koin_palsu = 1
    for k, v in cek_koin.items():
        if v == 1:
            koin_palsu = k
    for i in range(1, n):
        if coins[i] == koin_palsu:
            return i+1
        
print(find_fake_coin())